### ISSUE TITLE
Why not allowing partial keyframes, like CSS?

### ISSUE THREAD

**Issue by caub** [w3c/web-animations#187]
CSS allows:
```css
.loading {
	animation: loading 1s infinite ease-in-out;
}
@keyframes loading {
	50% {
		filter: brightness(2);
	}
}
```
so in JS, this would be great:
```js
var a = el.animate([{filter:'brightness(2)', offset:.5}], {duration:1000, iterations:Infinity});
```

But for now, the only way is
```js
var a = el.animate([
	{filter:'brightness(1)'}, 
	{filter:'brightness(2)', offset:.5}, 
	{filter:'brightness(1)'}
], {duration:1000, iterations:Infinity})
```
